# Generated by Django 5.2.17 on 2026-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='night_diff_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
