# Generated by Django 5.2.17 on 2026-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_night_diff_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='time_in_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
