# Generated by Django 5.2.17 on 2026-09-25 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_shift_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default=datetime.time(9, 0))),
                ('end', models.TimeField(default=datetime.time(18, 0))),
            ],
        ),
    ]
