# Generated by Django 5.2.17 on 2026-10-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="late_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
